import Head from 'next/head';
import Post from '../components/Posts';
import { useGetPosts, usePaginatePosts } from '../components/useRequest';

export default function Home() {
  // const { data: posts, error } = useGetPosts();

  // if (error) return <h1>Something went wrong!</h1>;
  // if (!posts) return <h1>Loading...</h1>;

  const { posts, error, isLoadingMore, size, setSize, isReachingEnd } =
    usePaginatePosts();

  if (error) return <h1>Something went wrong!</h1>;
  if (!posts) return <h1>Loading...</h1>;

  return (
    <div>
      <Head>
        <title>Next SWR App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-xl mx-auto">
        <h1 className="font-bold m-5">My Posts</h1>
        {posts.map((post) => (
          <Post post={post} key={post.id} />
        ))}
        <button
          className="bg-blue-500 text-white font-bold px-2 rounded mb-10"
          disabled={isLoadingMore || isReachingEnd}
          onClick={() => setSize(size + 1)}
        >
          {isLoadingMore
            ? 'Loading...'
            : isReachingEnd
            ? 'No more posts'
            : 'Load more'}
        </button>
      </main>
    </div>
  );
}
